import React from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { motion } from 'framer-motion';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { AlertCircle } from 'lucide-react';

const DNRFollowupsPage: React.FC = () => {
  const { user, role } = useAuth();

  const { data: leads, isLoading } = useQuery({
    queryKey: ['dnr-leads'],
    queryFn: async () => {
      const { data } = await supabase
        .from('leads')
        .select('*')
        .in('lead_status', ['DNR1', 'DNR2', 'DNR3', 'Non Interested'])
        .order('updated_at', { ascending: false });
      return data || [];
    },
    enabled: !!user,
  });

  const { data: profilesMap } = useQuery({
    queryKey: ['profiles-map-dnr'],
    queryFn: async () => {
      const { data } = await supabase.from('profiles').select('user_id, full_name, email');
      const map: Record<string, { full_name: string; email: string }> = {};
      data?.forEach(p => { map[p.user_id] = { full_name: p.full_name, email: p.email }; });
      return map;
    },
    enabled: !!user,
  });

  // BD members see only their own DNR leads
  const filtered = leads?.filter(l => {
    if (role === 'LEAD_GEN') return l.lead_generated_by === user?.id;
    return true;
  }) || [];

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2">
        <AlertCircle className="h-5 w-5 text-orange-500" />
        <h1 className="text-2xl font-display font-bold">DNR Follow-ups</h1>
      </div>

      <Card className="glass-card">
        <CardContent className="p-0">
          {isLoading ? (
            <div className="p-8 text-center text-muted-foreground">Loading...</div>
          ) : filtered.length === 0 ? (
            <div className="p-8 text-center text-muted-foreground">No DNR leads</div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="border-b border-border">
                    <th className="text-left p-3 font-medium text-muted-foreground">ID</th>
                    <th className="text-left p-3 font-medium text-muted-foreground">Name</th>
                    <th className="text-left p-3 font-medium text-muted-foreground">Email</th>
                    <th className="text-left p-3 font-medium text-muted-foreground">Phone</th>
                    <th className="text-left p-3 font-medium text-muted-foreground">Status</th>
                    <th className="text-left p-3 font-medium text-muted-foreground">Generated By</th>
                    <th className="text-left p-3 font-medium text-muted-foreground">Last Updated</th>
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((lead, i) => {
                    const gen = lead.lead_generated_by && profilesMap?.[lead.lead_generated_by];
                    return (
                      <motion.tr
                        key={lead.unique_id}
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: i * 0.03 }}
                        className="border-b border-border/50 hover:bg-accent/30 transition-colors"
                      >
                        <td className="p-3 text-xs font-mono text-muted-foreground">{(lead as any).display_id || '—'}</td>
                        <td className="p-3 font-medium">{lead.name}</td>
                        <td className="p-3 text-muted-foreground">{lead.email}</td>
                        <td className="p-3 text-muted-foreground">{lead.phone}</td>
                        <td className="p-3">
                          <Badge variant="secondary" className="bg-orange-500/10 text-orange-600">{lead.lead_status}</Badge>
                        </td>
                        <td className="p-3 text-xs">
                          {gen ? `${gen.full_name}` : '—'}
                        </td>
                        <td className="p-3 text-xs text-muted-foreground">
                          {new Date(lead.updated_at).toLocaleDateString()}
                        </td>
                      </motion.tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default DNRFollowupsPage;
